#!/bin/bash
# create_idr_virtual_env 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

main() {
    set -x
    sudo mv /etc/apt/apt.conf.d/99dnanexus /tmp
    sudo add-apt-repository -y ppa:fkrull/deadsnakes
    sudo apt-get update
    sudo apt-get -y install python3.4 python3.4-dev libfreetype6-dev
    sudo pip install virtualenv

    virtualenv --always-copy --python=python3.4 encode
    source encode/bin/activate
    pip install numpy
    pip install scipy
    pip install matplotlib

    git clone --recursive https://github.com/nboley/idr.git
    cd idr
    python setup.py install
    cd ..
    deactivate

    cp -R /usr/lib/python3.4/* encode/lib/python3.4/.

    tar zcvf encode_idr_virtual_env.tar.gz /home/dnanexus/encode


    virtual_env=$(dx upload encode_idr_virtual_env.tar.gz --brief)
    dx-jobutil-add-output virtual_env "$virtual_env" --class=file
}
