% Script for compiling align2rawsignal.m
clear all;
clc;
close all;
% Compile command
mcc -R nodisplay ...
    -m ...
    -o 'align2rawsignal' ...
    -d '../bin' ...
    -v ...
    'align2rawsignal.m';

! rm ../bin/*align2rawsignal*.c ../bin/*align2rawsignal*.prj ../bin/*.log ../bin/*align2rawsignal*.sh ../bin/readme.txt
